### ISSUE TITLE
Strange error with redis pubusub.

### ISSUE THREAD

**Issue by qwexvf** [gorilla/websocket#264]
```Go
2017/07/10 23:24:09 error on ws. message websocket: close 1000 (normal)
2017/07/10 23:24:09 error on ws. message websocket: close 1000 (normal)
2017/07/10 23:24:09 error on ws. message websocket: close 1000 (normal)
2017/07/10 23:24:09 http: panic serving 127.0.0.1:61199: repeated read on failed websocket connection
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc420094960)
        /usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1721 +0xd0
panic(0x1288160, 0xc42037f3e0)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/gorilla/websocket.(*Conn).NextReader(0xc420102000, 0x12879a0, 0x10, 0xc42037f3b8, 0x0, 0xc42004dbb0)
        /Users/qwexvf/code/go-local/src/github.com/gorilla/websocket/conn.go:958 +0x175
github.com/gorilla/websocket.(*Conn).ReadJSON(0xc420102000, 0x127af40, 0xc420158f20, 0xc420158ec0, 0x2)
        /Users/qwexvf/code/go-local/src/github.com/gorilla/websocket/json.go:45 +0x2f
main.wsHandler(0x1422480, 0xc4200f6000, 0xc42000a800)
        /Volumes/backup/projects/servermanager/websocket_server/ws_pubsub.go:112 +0x186
net/http.HandlerFunc.ServeHTTP(0x13022e8, 0x1422480, 0xc4200f6000, 0xc42000a800)
        /usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x144e560, 0x1422480, 0xc4200f6000, 0xc42000a800)
        /usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4200a22c0, 0x1422480, 0xc4200f6000, 0xc42000a800)
        /usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420094960, 0x14229c0, 0xc420018740)
        /usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2668 +0x2ce
```
Actual Code that i'm trying to run.

```Go
func wsHandler(w http.ResponseWriter, r *http.Request) {
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Printf("upgrader error %s\n" + err.Error())
		return
	}
	u := gStore.newUser(conn)
	log.Printf("user %s joined\n", u.ID)

	for {
		var m Message

		if err := u.conn.ReadJSON(&m); err != nil {
			log.Printf("error on ws. message %s\n", err)
		}

		if c, err := gRedisConn(); err != nil {
			log.Printf("error on redis conn. %s\n", err)
                        // sounds like i forget to close connection here sorry..
		} else {
			c.Do("PUBLISH", m.DeliveryID, string(m.Content))
		}
	}
}
```

please close this issue.

**Comment by garyburd** [comment]
Exit the loop and close the connection when read on the connection returns an error.

**Comment by qwexvf** [comment]
thank you @garyburd. i was struggling with a piece of code .....
Please close this issue.
