### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by xrfang** [gorilla/websocket#289]
I have a panic in my websocket application, which is generated within gorilla. stack trace:

```
panic: runtime error: slice bounds out of range

goroutine 1393 [running]:
io/ioutil.readAll.func1(0xc4204b4e50)
        /usr/local/go/src/io/ioutil/ioutil.go:30 +0x119
panic(0x7a05a0, 0x9de330)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
bufio.(*Reader).Read(0xc4201f9440, 0xc42013c800, 0x200, 0x200, 0x100000000000000, 0x0, 0x200)
        /usr/local/go/src/bufio/bufio.go:224 +0x4c1
github.com/gorilla/websocket.(*messageReader).Read(0xc42000e200, 0xc42013c800, 0x200, 0x200, 0x4293de, 0xc400000008, 0xc420127f00)
        /home/xrfang/git/hermes/src/github.com/gorilla/websocket/conn.go:978 +0x269
bytes.(*Buffer).ReadFrom(0xc4204b4da8, 0x7fdae7493310, 0xc42000e200, 0xc42013c800, 0x0, 0x200)
        /usr/local/go/src/bytes/buffer.go:179 +0x160
io/ioutil.readAll(0x7fdae7493310, 0xc42000e200, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:33 +0x150
io/ioutil.ReadAll(0x7fdae7493310, 0xc42000e200, 0x7fdae7493310, 0xc42000e200, 0x0, 0x0, 0xc4204b4ec0)
        /usr/local/go/src/io/ioutil/ioutil.go:42 +0x3e
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc4204237c0, 0x821698, 0xc4203fe7f0, 0x739430, 0xc4203fe7d0, 0x1, 0xc420512c00)
        /home/xrfang/git/hermes/src/github.com/gorilla/websocket/conn.go:1023 +0x97
main.porch.Read(0xc4204237c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/xrfang/git/hermes/src/hermesd/mundi.go:39 +0x12f
main.ws.func3(0xc420131480, 0xc4201316a0)
        /home/xrfang/git/hermes/src/hermesd/ws.go:43 +0x49
created by main.ws
        /home/xrfang/git/hermes/src/hermesd/ws.go:51 +0x36d
panic: runtime error: slice bounds out of range

goroutine 1393 [running]:
io/ioutil.readAll.func1(0xc4204b4e50)
        /usr/local/go/src/io/ioutil/ioutil.go:30 +0x119
panic(0x7a05a0, 0x9de330)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
bufio.(*Reader).Read(0xc4201f9440, 0xc42013c800, 0x200, 0x200, 0x100000000000000, 0x0, 0x200)
        /usr/local/go/src/bufio/bufio.go:224 +0x4c1
github.com/gorilla/websocket.(*messageReader).Read(0xc42000e200, 0xc42013c800, 0x200, 0x200, 0x4293de, 0xc400000008, 0xc420127f00)
        /home/xrfang/git/hermes/src/github.com/gorilla/websocket/conn.go:978 +0x269
bytes.(*Buffer).ReadFrom(0xc4204b4da8, 0x7fdae7493310, 0xc42000e200, 0xc42013c800, 0x0, 0x200)
        /usr/local/go/src/bytes/buffer.go:179 +0x160
io/ioutil.readAll(0x7fdae7493310, 0xc42000e200, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:33 +0x150
io/ioutil.ReadAll(0x7fdae7493310, 0xc42000e200, 0x7fdae7493310, 0xc42000e200, 0x0, 0x0, 0xc4204b4ec0)
        /usr/local/go/src/io/ioutil/ioutil.go:42 +0x3e
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc4204237c0, 0x821698, 0xc4203fe7f0, 0x739430, 0xc4203fe7d0, 0x1, 0xc420512c00)
        /home/xrfang/git/hermes/src/github.com/gorilla/websocket/conn.go:1023 +0x97
main.porch.Read(0xc4204237c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/xrfang/git/hermes/src/hermesd/mundi.go:39 +0x12f
main.ws.func3(0xc420131480, 0xc4201316a0)
        /home/xrfang/git/hermes/src/hermesd/ws.go:43 +0x49
created by main.ws
        /home/xrfang/git/hermes/src/hermesd/ws.go:51 +0x36d

```

My code related to this crash is attached below.

[src.zip](https://github.com/gorilla/websocket/files/1371008/src.zip)

**Comment by xrfang** [comment]
a detailed trace:

```
2017-10-10 16:03:36 [ERROR] ws: runtime error: slice bounds out of range
#0: ws: runtime error: slice bounds out of range
#1: 
#2: (bufio/bufio.go:224) bufio.(*Reader).Read
#3: (io/io.go:436) io.(*LimitedReader).Read
#4: (io/ioutil/ioutil.go:144) io/ioutil.devNull.ReadFrom
#5: (<autogenerated>:6) io/ioutil.(*devNull).ReadFrom
#6: (io/io.go:384) io.copyBuffer
#7: (io/io.go:360) io.Copy
#8: (io/io.go:336) io.CopyN
#9: (github.com/gorilla/websocket/conn.go:771) github.com/gorilla/websocket.(*Conn).advanceFrame
#10: (github.com/gorilla/websocket/conn.go:938) github.com/gorilla/websocket.(*Conn).NextReader
#11: (github.com/gorilla/websocket/conn.go:1019) github.com/gorilla/websocket.(*Conn).ReadMessage
#12: (hermesd/mundi.go:39) main.porch.Read
#13: (hermesd/ws.go:52) main.ws.func3

```

**Comment by garyburd** [comment]
Run the application with the [race detector](https://golang.org/doc/articles/race_detector.html), fix any errors and report back if there's still a problem.

**Comment by xrfang** [comment]
I upgraded go from 1.8.3 to 1.9.1, this problem is gone, however there are frequently runtime errors about receiving a invalid byte sequence etc. is it caused by race conditions also? thanks.

**Comment by garyburd** [comment]
The panic is probably caused by a data race in the application. Run the race detector and fix all issues.
