### ISSUE TITLE
concurrent map writes error in coroutines

### ISSUE THREAD

**Issue by BigVan** [gorilla/websocket#293]
Hello~
    I write a server-client test program and do some stress test.

- On the server side:
    read message from *conn and return message what it read. After receive 50 times message, server will close the connection.

- On the client side:
    use goroutinue send "hello world" to server and write response message to files.

Whereas, when I use multiple coroutines, it shows "concurrent map writes"...

How should I do ?

Here is my code:

- server:
```
var upgrader = websocket.Upgrader{} // use default options
func echo(w http.ResponseWriter, r *http.Request) {
	c, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Print("upgrade:", err)
		return
	}
	defer c.Close()
	count := 50
	for {
		if count <= 0 {
			break
		}
		mt, message, err := c.ReadMessage()
		if err != nil {
			log.Println("read:", err)
			break
		}
		err = c.WriteMessage(mt, message)
		if err != nil {
			log.Println("write:", err)
			break
		}
		count--
	}
}

func main() {
	log.Println("start")
	http.HandleFunc("/echo", echo)
	log.Fatal(http.ListenAndServe(*addr, nil))
}
```

 - client:

```
func PushAudio(signal chan int, idx int) {

	addr := flag.String(fmt.Sprintf("addr_%d", idx), "localhost:8080", "")
	u := url.URL{Scheme: "ws", Host: *addr, Path: "/echo"}
	log.Printf("connecting to %s", u.String())
	c, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
	if err != nil {
		log.Fatal("dial:", err)
	}
	defer c.Close()
	f, _ := os.Create(fmt.Sprintf("test_%d.txt", idx))
	defer f.Close()
	ch := make(chan int)

	go func() {
		for {
			_, message, err := c.ReadMessage()
			if err != nil {
				log.Println("read:", err)				
				break
			}
			f.Write(message)
		}
		ch <- 1
	}()
	for {
		err := c.WriteMessage(websocket.TextMessage, []byte("hello world\n"))
		if err != nil {
			log.Println("write:", err)
			break
		}
	}
	<-ch
	signal <- 1
}

func TestClient(t *testing.T) {

	parallel_size := 100
	chanset := make(chan int, parallel_size)

	for i := 0; i < parallel_size; i++ {		
		go PushAudio(chanset, i)
	}
	for i := 0; i < parallel_size; i++ {
		<-chanset
	}

}

```

Here a part of exception message:
```
2017/10/27 20:27:20 connecting to ws://localhost:8080/echo
2017/10/27 20:27:20 connecting to ws://localhost:8080/echo
fatal error: 2017/10/27 20:27:20 connecting to ws://localhost:8080/echo
concurrent map writes

goroutine 8 [running]:
runtime.throw(0x86a0c0, 0x15)
        /usr/lib/go-1.6/src/runtime/panic.go:547 +0x90 fp=0xc82018baf8 sp=0xc82018bae0
runtime.mapassign1(0x70efa0, 0xc8200102d0, 0xc82018bc58, 0xc82018bbf0)
        /usr/lib/go-1.6/src/runtime/hashmap.go:445 +0xb1 fp=0xc82018bba0 sp=0xc82018baf8
flag.(*FlagSet).Var(0xc820074060, 0x7ff9dedf01c0, 0xc8201ae080, 0xc8201ae070, 0x6, 0x0, 0x0)
        /usr/lib/go-1.6/src/flag/flag.go:781 +0x75c fp=0xc82018bcb8 sp=0xc82018bba0
flag.(*FlagSet).StringVar(0xc820074060, 0xc8201ae080, 0xc8201ae070, 0x6, 0x8323d0, 0xe, 0x0, 0x0)
        /usr/lib/go-1.6/src/flag/flag.go:679 +0xc7 fp=0xc82018bd28 sp=0xc82018bcb8
flag.(*FlagSet).String(0xc820074060, 0xc8201ae070, 0x6, 0x8323d0, 0xe, 0x0, 0x0, 0x6)
        /usr/lib/go-1.6/src/flag/flag.go:692 +0x83 fp=0xc82018bd78 sp=0xc82018bd28
flag.String(0xc8201ae070, 0x6, 0x8323d0, 0xe, 0x0, 0x0, 0x6)
        /usr/lib/go-1.6/src/flag/flag.go:699 +0x5f fp=0xc82018bdc0 sp=0xc82018bd78
coding.net/bigvan/websocket/test.PushAudio(0xc82007bc00, 0x2)
        /home/gowork/src/coding.net/bigvan/websocket/test/client_test.go:18 +0x168 fp=0xc82018bf90 sp=0xc82018bdc0
runtime.goexit()
        /usr/lib/go-1.6/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82018bf98 sp=0xc82018bf90
created by coding.net/bigvan/websocket/test.TestClient
        /home/gowork/src/coding.net/bigvan/websocket/test/client_test.go:64 +0x7a

goroutine 1 [chan receive]:
testing.RunTests(0x8d37a0, 0xa0e700, 0x1, 0x1, 0xc820098701)
        /usr/lib/go-1.6/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820053ef8, 0x70d120)
        /usr/lib/go-1.6/src/testing/testing.go:515 +0x81
main.main()
        coding.net/bigvan/websocket/test/_test/_testmain.go:54 +0x117

```

**Comment by garyburd** [comment]
Your application using the flag package incorrectly.  The flag.String function must not be called concurrently and must be called before flag.Parse. The concurrent calls to flag.String are causing the panic.

This issue is unrelated to the websocket package.

**Comment by BigVan** [comment]
Oh, I'm so sorry....
And thank you very much  !
