### ISSUE TITLE
Is WriteJSON method Thread Safe ?

### ISSUE THREAD

**Issue by hellojukay** [gorilla/websocket#341]
```shell
panic: concurrent write to websocket connection

goroutine 46 [running]:
gitlab.didapinche.com/plat_deploy/vendor/github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc4207dc630, 0x1, 0x0, 0x0, 0x0, 0xc4207e60b0, 0xc420718000)
	/deployment/ci/go_workspace/src/gitlab.didapinche.com/plat_deploy/vendor/github.com/gorilla/websocket/conn.go:585 +0x57b
gitlab.didapinche.com/plat_deploy/vendor/github.com/gorilla/websocket.(*messageWriter).Close(0xc4207dc630, 0xb134c0, 0xc420277480)
	/deployment/ci/go_workspace/src/gitlab.didapinche.com/plat_deploy/vendor/github.com/gorilla/websocket/conn.go:699 +0x60
gitlab.didapinche.com/plat_deploy/vendor/github.com/gorilla/websocket.(*Conn).WriteJSON(0xc4202a9540, 0xb134c0, 0xc420277480, 0xc420277480, 0xc4202e3e79)
	/deployment/ci/go_workspace/src/gitlab.didapinche.com/plat_deploy/vendor/github.com/gorilla/websocket/json.go:27 +0x112
gitlab.didapinche.com/plat_deploy/router.websocketSyncLog(0xc420012527, 0x5, 0xc4202a9540, 0xed5860, 0xc4201ca5d8, 0xed5860, 0xc4201ca5d8)
	/deployment/ci/go_workspace/src/gitlab.didapinche.com/plat_deploy/router/routers.go:245 +0x1f9
gitlab.didapinche.com/plat_deploy/router.restartInstance(0xc4202a9540, 0xc4206bcd20, 0x44, 0xc42022c7d0, 0xe, 0x2, 0xc420012530, 0xd, 0xc420012527, 0x5, ...)
	/deployment/ci/go_workspace/src/gitlab.didapinche.com/plat_deploy/router/restart.go:326 +0xa80
gitlab.didapinche.com/plat_deploy/router.restartHost(0x2, 0xc420012530, 0xd, 0xc420012527, 0x5, 0x0, 0x0, 0x0, 0xc42008e000, 0x2462, ...)
	/deployment/ci/go_workspace/src/gitlab.didapinche.com/plat_deploy/router/restart.go:209 +0x4cc
gitlab.didapinche.com/plat_deploy/router.RestartApp.func1(0xc42022daf0, 0xc4202e2930, 0xc42008e000, 0xc4202ce840, 0xc42022c7d0, 0xe, 0xc4202c3e25, 0x6, 0xc4202a9540, 0xc42022d818, ...)
	/deployment/ci/go_workspace/src/gitlab.didapinche.com/plat_deploy/router/restart.go:154 +0xff
created by gitlab.didapinche.com/plat_deploy/router.RestartApp
	/deployment/ci/go_workspace/src/gitlab.didapinche.com/plat_deploy/router/restart.go:158 +0x18d8
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)
```

**Comment by garyburd** [comment]
Concurrent write calls are not supported as indicated by the panic message.

[Documentation](https://godoc.org/github.com/gorilla/websocket#hdr-Concurrency).
