### ISSUE TITLE
How to reconnect connction,thanks

### ISSUE THREAD

**Issue by guojun1992** [gorilla/websocket#362]
```
panic: repeated read on failed websocket connection

goroutine 92 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0xc42017a000, 0x4bce1c, 0xc42006e0f0, 0x2, 0xc5b8881ce0, 0x22)
	/home/guojun/goSpace/src/github.com/gorilla/websocket/conn.go:960 +0x3d9
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc42017a000, 0x2, 0x2, 0x0, 0x0, 0x892cc0, 0xc420040070)
	/home/guojun/goSpace/src/github.com/gorilla/websocket/conn.go:1021 +0x2f
yinxing_spider/spider.(*HuobiTrait).HandleMessage.func1(0xc42017a000)
	/home/guojun/goSpace/src/yinxing_spider/spider/huobi.go:133 +0x6e
created by yinxing_spider/spider.(*HuobiTrait).HandleMessage
	/home/guojun/goSpace/src/yinxing_spider/spider/huobi.go:129 +0x5e5
```

how to reconnect connction?thanks

**Comment by garyburd** [comment]
The panic indicates that the application is ignoring the error returned from ReadMessage.  The application should exit its read loop and close the connection when ReadMessage returns an error.

The application is responsible for reconnecting to the server.
