### ISSUE TITLE
[bug] when request: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fbens** [gorilla/websocket#523]
**Describe the bug**
> A clear and concise description of what the bug is.
When send websocket request, the server down with error "runtime error: invalid memory address or nil pointer dereference"
…

**Versions**
> Go version: `go version go1.12.7 windows/amd64`
> package version: run `git rev-parse HEAD` inside the repo
a531789774118f040b282adcfb2e21282330d788
…

**Steps to Reproduce**
> How can the bug be triggered?
When the client start connect to the websocket server
…

**Expected behavior**
> What output or behaviour were you expecting instead?
work ok. no error 
…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).
…
```go
func startWsServer(addr string, port string, path string) {
	if len(path) == 0 {
		path = "/"
	}

	http.HandleFunc(path, func(w http.ResponseWriter, r *http.Request) {
		conn, _ := upgrader.Upgrade(w, r, nil)

		for {
			msgType, msg, err := conn.ReadMessage()
			if err != nil {
				log.Println(err)
				return
			}

			// fmt.Printf("%s sent: %s\n", conn.RemoteAddr(), string(msg))
			if err = conn.WriteMessage(msgType, msg); err != nil {
				log.Println(err)
				return
			}
		}
	})

	// http.HandleFunc("/",func(w http.ResponseWriter,r *http.Request){
	// 	http.ServeFile(w, r, "websockets.html")
	// })

	fmt.Println("Start Listen ws://"+addr+":"+port+path)
	http.ListenAndServe(addr+":"+port, nil)
}
```

**Message**
> Output message
```shell
D:\Google\golang\src\first>go run demo.go -d start
Start Listen ws://127.0.0.1:17505/
2019/07/16 16:56:25 http: panic serving 127.0.0.1:50168: runtime error: invalid memory address or nil pointer dereference
goroutine 19 [running]:
net/http.(*conn).serve.func1(0xc00004aa00)
        c:/go/src/net/http/server.go:1769 +0x140
panic(0x6c70e0, 0x96e2c0)
        c:/go/src/runtime/panic.go:522 +0x1c3
github.com/gorilla/websocket.(*Conn).NextReader(0x0, 0x9, 0x4296de, 0x6, 0xc00001ca88, 0xc00001ca00)
        C:/Users/Administrator/go/src/github.com/gorilla/websocket/conn.go:936 +0x2d
github.com/gorilla/websocket.(*Conn).ReadMessage(0x0, 0x786240, 0xc00010e000, 0xc0000fa000, 0x0, 0x0, 0x7812e0)
        C:/Users/Administrator/go/src/github.com/gorilla/websocket/conn.go:1026+0x36
main.startWsServer.func1(0x786240, 0xc00010e000, 0xc0000fa000)
        D:/Google/golang/src/first/server.go:105 +0x79
net/http.HandlerFunc.ServeHTTP(0x7351b0, 0x786240, 0xc00010e000, 0xc0000fa000)
        c:/go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0x97a0c0, 0x786240, 0xc00010e000, 0xc0000fa000)
        c:/go/src/net/http/server.go:2375 +0x1dd
net/http.serverHandler.ServeHTTP(0xc000049110, 0x786240, 0xc00010e000, 0xc0000fa000)
        c:/go/src/net/http/server.go:2774 +0xaf
net/http.(*conn).serve(0xc00004aa00, 0x786780, 0xc0000ec040)
        c:/go/src/net/http/server.go:1878 +0x858
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2884 +0x2fb
exit status 2

```

**Comment by elithrar** [comment]
You need to handle the error here:

> conn, _ := upgrader.Upgrade(w, r, nil)

**Comment by fbens** [comment]
> You need to handle the error here:
>

Thank you very much.It's ok now. :-) :-)

Error:
```
2019/07/16 21:30:51 websocket: request origin not allowed by Upgrader.CheckOrigin
2019/07/16 21:30:51 http: panic serving 127.0.0.1:65247: websocket: request origin not allowed by Upgrader.CheckOrigin
```

solution:
```go
upgrader.CheckOrigin = func(r *http.Request) bool { return true }
```

**Comment by elithrar** [comment]
You should validate the origin, or use a flag to only bypass origin
checking in dev environments.
