### ISSUE TITLE
Lots of errors: goroutine X [select] / [IO Wait] / [runnable]

### ISSUE THREAD

**Issue by marklonquist** [gorilla/websocket#598]
**Describe the problem you're having**

Following the chat example (with some modifications of course), we're getting a high amount of errors in our logs;
```
E 2020-06-07T17:14:20.768051426Z goroutine 945 [select]:
E 2020-06-07T17:14:20.768056723Z bitbucket.org/fundayfactory/bullet-league-backend/services/social/internal/social/hub.(*Hub).Send(0xc0003ad080, 0xc00130b200)
E 2020-06-07T17:14:20.768060978Z 	/home/teamcity-agents/work/backend-01/17f2ab2d9f13ee24/services/social/internal/social/hub/hub.go:124 +0x136
E 2020-06-07T17:14:20.768064935Z created by main.(*Endpoints).ServeWs
E 2020-06-07T17:14:20.768068647Z 	/home/teamcity-agents/work/backend-01/17f2ab2d9f13ee24/services/social/cmd/social/endpoints.go:121 +0xb03
```

```
E 2020-06-07T17:14:20.768028245Z goroutine 944 [runnable]:
E 2020-06-07T17:14:20.768031933Z bitbucket.org/fundayfactory/bullet-league-backend/services/social/internal/social/hub.(*Hub).Send(0xc0003ad080, 0xc00130b170)
E 2020-06-07T17:14:20.768035909Z 	/home/teamcity-agents/work/backend-01/17f2ab2d9f13ee24/services/social/internal/social/hub/hub.go:124 +0x136
E 2020-06-07T17:14:20.768039979Z created by main.(*Endpoints).ServeWs
E 2020-06-07T17:14:20.768043765Z 	/home/teamcity-agents/work/backend-01/17f2ab2d9f13ee24/services/social/cmd/social/endpoints.go:121 +0xb03
```

It ends up causing our service to be restarted by kubernetes.

---

**Versions**
> Go version

go1.14
> package version

github.com/gorilla/websocket v1.4.2

---

**"Show me the code!"**

```go
func (e *Endpoints) ServeWs(w http.ResponseWriter, r *http.Request) {

        // some code left out for readability

	client := hubmodels.NewClient(userId, socialId, playerAppearance, state, f, conn)
	e.Hub.Register <- client

	go e.Hub.Send(client)
	e.Hub.Receive(client)
}
```

```go
func (h *Hub) Run() {
	for {
		select {
		case client := <-h.Register:
			h.Clients[client.SocialID] = client
			err := h.handlers[hubmessagetype.StateChangeInternal].HandleMessage(client, incoming.NewStateChange(client.State, true))
			if err != nil {
				h.Log(err)
			}
			client.Data <- messages.NewClientInit(client.Friends, client.SocialID)
		case client := <-h.Unregister:
			if _, ok := h.Clients[client.SocialID]; ok {
				if client.Kicked {
					continue
				}

				delete(h.Clients, client.SocialID)
				close(client.Data)
			}
		}
	}
}

func (h *Hub) Receive(c *hub.Client) {
	defer func() {
		h.Unregister <- c
		c.Conn.Close()
	}()

	c.Conn.SetReadLimit(constants.MaxMessageSize)
	c.Conn.SetReadDeadline(time.Now().Add(constants.PongWait))
	c.Conn.SetPongHandler(func(string) error { c.Conn.SetReadDeadline(time.Now().Add(constants.PongWait)); return nil })

	for {
		_, b, err := c.Conn.ReadMessage()
		if err != nil {
			h.Log(err)
			return
		}

		var message messages.MessageBase
		if err := json.Unmarshal(b, &message); err != nil {
			h.Log(err)
			return
		}

		if handler, ok := h.handlers[message.MessageType]; ok {
			c.Conn.SetReadDeadline(time.Now().Add(constants.PongWait))
			if err := handler.HandleMessage(c, string(b)); err != nil {
				h.Log(err)
				return
			}
		} else {
			h.Log(errorf.New("Message type " + message.MessageType.String() + " not implemented."))
		}
	}
}

func (h *Hub) Send(c *hub.Client) {
	ticker := time.NewTicker(constants.PingPeriod)
	defer func() {
		ticker.Stop()
		c.Conn.Close()
	}()

	for {
		select { // !! NOTICE !! this is line 124
		case message, ok := <-c.Data:
			c.Conn.SetWriteDeadline(time.Now().Add(constants.WriteWait))
			if !ok {
				c.Conn.WriteMessage(websocket.CloseMessage, []byte{})
				return
			}

			if err := c.Conn.WriteJSON(message); err != nil {
				h.Log(err)
				return
			}
		case <-ticker.C:
			c.Conn.SetWriteDeadline(time.Now().Add(constants.WriteWait))
			if err := c.Conn.WriteMessage(websocket.PingMessage, []byte{}); err != nil {
				h.PingLog(err)
				return
			}
		}
	}
}
```

**Comment by AlbiDalbi** [comment]
It is not surprising that goroutines are at the `select`.   If these stack traces are the result of a panic, then show the panic message and the stack trace of the first goroutine after the panic message.

**Comment by marklonquist** [comment]
@AlbiDalbi thank you - because of you I decided to add a log message as the service starts up and found that it fatals with `fatal error: concurrent map read and map write` - this is followed by a ton of those goroutine stacktrackes.

For clarity, this is the first stacktrace after the fatal error;
```
I 2020-06-09T07:05:30.895766577Z HTTP running on port: 80 
I 2020-06-09T07:05:30.895850877Z grpc running on port: 9111 
E 2020-06-09T07:05:57.836277306Z fatal error: concurrent map read and map write
E 2020-06-09T07:05:57.839671200Z 
E 2020-06-09T07:05:57.839918719Z goroutine 475 [running]:
E 2020-06-09T07:05:57.839971689Z runtime.throw(0x103a2fd, 0x21)
E 2020-06-09T07:05:57.839980440Z 	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc000b5b520 sp=0xc000b5b4f0 pc=0x42e302
E 2020-06-09T07:05:57.839988708Z runtime.mapaccess2_faststr(0xe8ee00, 0xc0003e18c0, 0xc000c962a0, 0x1e, 0x1e, 0x0)
E 2020-06-09T07:05:57.843729125Z 	/usr/local/go/src/runtime/map_faststr.go:116 +0x48f fp=0xc000b5b590 sp=0xc000b5b520 pc=0x412c4f
E 2020-06-09T07:05:57.843763085Z main.(*Endpoints).ServeWs(0xc000256a00, 0x12f0c20, 0xc00064e7e0, 0xc000b88e00)
E 2020-06-09T07:05:57.843797796Z 	/home/teamcity-agents/work/backend-02/dadb1adf2f054add/services/social/cmd/social/endpoints.go:73 +0x12e fp=0xc000b5b850 sp=0xc000b5b590 pc=0xd995de
E 2020-06-09T07:05:57.843806750Z main.(*Endpoints).ServeWs-fm(0x12f0c20, 0xc00064e7e0, 0xc000b88e00)
E 2020-06-09T07:05:57.843813986Z 	/home/teamcity-agents/work/backend-02/dadb1adf2f054add/services/social/cmd/social/endpoints.go:60 +0x48 fp=0xc000b5b880 sp=0xc000b5b850 pc=0xd9cf28
E 2020-06-09T07:05:57.843822180Z net/http.HandlerFunc.ServeHTTP(0xc0001bc8d0, 0x12f0c20, 0xc00064e7e0, 0xc000b88e00)
E 2020-06-09T07:05:57.843829403Z 	/usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc000b5b8a8 sp=0xc000b5b880 pc=0x6cd804
E 2020-06-09T07:05:57.843836556Z bitbucket.org/fundayfactory/bullet-league-backend/shared/jwt.(*FirebaseJWT).FirebaseAuthentication.func1(0x12f0c20, 0xc00064e7e0, 0xc000b88400)
E 2020-06-09T07:05:57.843844055Z 	/home/teamcity-agents/work/backend-02/dadb1adf2f054add/shared/jwt/jwtmiddleware.go:166 +0x30f fp=0xc000b5b990 sp=0xc000b5b8a8 pc=0xd9030f
E 2020-06-09T07:05:57.843851339Z net/http.HandlerFunc.ServeHTTP(0xc00000d140, 0x12f0c20, 0xc00064e7e0, 0xc000b88400)
E 2020-06-09T07:05:57.843874013Z 	/usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc000b5b9b8 sp=0xc000b5b990 pc=0x6cd804
E 2020-06-09T07:05:57.843881938Z github.com/gorilla/mux.(*Router).ServeHTTP(0xc00024e840, 0x12f0c20, 0xc00064e7e0, 0xc000b88200)
E 2020-06-09T07:05:57.843889013Z 	/home/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2 fp=0xc000b5bae0 sp=0xc000b5b9b8 pc=0xb6eeb2
E 2020-06-09T07:05:57.843896344Z github.com/gorilla/handlers.(*cors).ServeHTTP(0xc00034e990, 0x12f0c20, 0xc00064e7e0, 0xc000b88200)
E 2020-06-09T07:05:57.843903437Z 	/home/go/pkg/mod/github.com/gorilla/handlers@v1.4.2/cors.go:54 +0x1037 fp=0xc000b5bc18 sp=0xc000b5bae0 pc=0xb6d7a7
E 2020-06-09T07:05:57.843910960Z net/http.serverHandler.ServeHTTP(0xc0002a0000, 0x12f0c20, 0xc00064e7e0, 0xc000b88200)
E 2020-06-09T07:05:57.843918212Z 	/usr/local/go/src/net/http/server.go:2802 +0xa4 fp=0xc000b5bc48 sp=0xc000b5bc18 pc=0x6d0c54
E 2020-06-09T07:05:57.843962278Z net/http.(*conn).serve(0xc0004d3a40, 0x12f34e0, 0xc000c1cec0)
E 2020-06-09T07:05:57.843969123Z 	/usr/local/go/src/net/http/server.go:1890 +0x875 fp=0xc000b5bfc8 sp=0xc000b5bc48 pc=0x6cc5f5
E 2020-06-09T07:05:57.843975364Z runtime.goexit()
E 2020-06-09T07:05:57.843981206Z 	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000b5bfd0 sp=0xc000b5bfc8 pc=0x45afc1
E 2020-06-09T07:05:57.843987309Z created by net/http.(*Server).Serve
E 2020-06-09T07:05:57.843993445Z 	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

Guess I have to fix that :-)

**Comment by marklonquist** [comment]
Switching to syncmap.Map{} is the way forward from here I guess.. It's not a problem with Gorilla/Websocket, so closing this :-)
