### ISSUE TITLE
[bug] concurrent write to websocket connection

### ISSUE THREAD

**Issue by napsy** [gorilla/websocket#698]
**Describe the bug**

When a websocket write operation fails, a panic is triggered internally by the library:

```
panic: concurrent write to websocket connection

goroutine 11852 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc000a00e40, 0x1001, 0x0, 0x0, 0x0, 0x0, 0x64)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:591 +0x6ee
github.com/gorilla/websocket.(*messageWriter).Close(0xc000a00e40, 0x0, 0xc000407d58)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:709 +0x56
github.com/gorilla/websocket.(*Conn).prepWrite(0xc00055e160, 0x1, 0x0, 0x0)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:459 +0x222
github.com/gorilla/websocket.(*Conn).NextWriter(0xc00055e160, 0x1, 0x4, 0x8, 0x4, 0x0)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:494 +0x39
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc00055e160, 0x1, 0xc0001e8018, 0x4, 0x8, 0x43ea3c, 0xc000407e38)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:755 +0x6e
vss/pkg/websocket.(*Client).Send(0xc0003a6500, 0xc0001e8018, 0x4, 0x8)
```

…

I suspecnt that an internal flag that protects the socket from concurrent writing is not set correctly and triggers a panic.

**Versions**

> Go version: go version go1.15.8 linux/amd64
> package version: github.com/gorilla/websocket v1.4.0 h1:WDFjx/TMzVgy9VdMMQi2K2Emtwi2QcUQsztZ/zLaH/Q=

…

**Steps to Reproduce**

A write to the websocket fails.

…

**Expected behavior**

Internal handling of write failures should not trigger a concurrent write to the websocket.

**Comment by MonicaRJones** [comment]
Applications must not write concurrently to a connection ([documentation](https://godocs.io/github.com/gorilla/websocket#hdr-Concurrency)).  The flag is used in a [best effort attempt to detect concurrent writes](https://github.com/gorilla/websocket/blob/e8629af678b7fe13f35dff5e197de93b4148a909/conn.go#L605-L619).  The flag does not prevent concurrent writes.

Are you saying that the panic triggered in the absence of a concurrent write?  Does your application run without warnings with [the race detector](https://golang.org/doc/articles/race_detector)?

**Comment by Klikini** [comment]
My application started doing this today with no code changes to the client, but a new websocket library on the server. I am sure that I am not writing to the same socket from multiple goroutines because each goroutine opens its own socket to a different server path. In my application, goroutines may write to different sockets concurrently, but not the same socket.

**Comment by MonicaRJones** [comment]
Because the concurrent write detection code is simple and has been used by many applications over the last 5 years,  I am inclined to think the problem is with the application.  I could be wrong.  If your application runs clean with the  [race detector](https://golang.org/doc/articles/race_detector) , then there is something to investigate here.

@Klikini When you report back with the results running the race detector, it will be helpful if you tells us if your application is the client (w/ no code changes) or the server (w/ new websocket library).

**Comment by darluc** [comment]
I got the same problem too.
```
2021-08-07 19:43:13.491	github.com/gorilla/websocket.(*Conn).beginMessage(0xc0011ecf20, 0xc0010bb500, 0x1, 0xddddac3d65f, 0x1aa9600)
2021-08-07 19:43:13.491	/vendor/github.com/gorilla/websocket/conn.go:724 +0x65
2021-08-07 19:43:13.491	github.com/gorilla/websocket.(*messageWriter).Close(0xc00145ec00, 0x0, 0xc00170dbf8)
2021-08-07 19:43:13.491	/vendor/github.com/gorilla/websocket/conn.go:610 +0x62e
2021-08-07 19:43:13.491	github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc00145ec00, 0xd6ad01, 0x0, 0x0, 0x0, 0x7fc7d638b1d8, 0x30)
2021-08-07 19:43:13.491	goroutine 135 [running]:
2021-08-07 19:43:13.491	panic: concurrent write to websocket connection
```

**Comment by mamjsn** [comment]
@darluc It looks like your application calls the write methods concurrently, but that's not supported by the package.  Run your application with the [race detector](https://golang.org/doc/articles/race_detector) to find where the issues are.

**Comment by darluc** [comment]
@mamjsn  I'm connecting with multiple websocket clients, these clients may communicate with the server concurrently.
Do you mean I need a global write lock for all these clients/connections?
